[tool.poetry]
name = "zlabwiki"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mystmd = "^1.3.19"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
